In [5]:
from sklearn import datasets
import pandas as pd

In [2]:
boston = datasets.load_boston()

In [6]:
df = pd.DataFrame(boston.data)
df.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.593761,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.596783,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.647423,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [7]:
from sklearn import preprocessing

In [9]:
scaled_data = preprocessing.scale(boston.data)
df2 = pd.DataFrame(scaled_data)
df2.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02
mean,6.340997e-17,-6.343191e-16,-2.682911e-15,4.701992e-16,2.490322e-15,-1.145230e-14,-1.407855e-15,9.210902e-16,5.441409e-16,-8.868619e-16,-9.205636e-15,8.163101e-15,-3.370163e-16
std,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00
min,-4.177134e-01,-4.877224e-01,-1.557842e+00,-2.725986e-01,-1.465882e+00,-3.880249e+00,-2.335437e+00,-1.267069e+00,-9.828429e-01,-1.313990e+00,-2.707379e+00,-3.907193e+00,-1.531127e+00
25%,-4.088961e-01,-4.877224e-01,-8.676906e-01,-2.725986e-01,-9.130288e-01,-5.686303e-01,-8.374480e-01,-8.056878e-01,-6.379618e-01,-7.675760e-01,-4.880391e-01,2.050715e-01,-7.994200e-01
50%,-3.885818e-01,-4.877224e-01,-2.110985e-01,-2.725986e-01,-1.442174e-01,-1.084655e-01,3.173816e-01,-2.793234e-01,-5.230014e-01,-4.646726e-01,2.748590e-01,3.811865e-01,-1.812536e-01
75%,6.248255e-03,4.877224e-02,1.015999e+00,-2.725986e-01,5.986790e-01,4.827678e-01,9.067981e-01,6.623709e-01,1.661245e+00,1.530926e+00,8.065758e-01,4.336510e-01,6.030188e-01
max,9.941735e+00,3.804234e+00,2.422565e+00,3.668398e+00,2.732346e+00,3.555044e+00,1.117494e+00,3.960518e+00,1.661245e+00,1.798194e+00,1.638828e+00,4.410519e-01,3.548771e+00

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(scaled_data, boston.target)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
clf = LinearRegression()

In [20]:
clf.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
clf.score(x_test, y_test)

0.77973335602386085

In [22]:
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target)

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler = StandardScaler()
#scaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [28]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [29]:
df3 = pd.DataFrame(x_train_scaled)
df3.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02,3.790000e+02
mean,-2.432824e-16,-1.154163e-16,2.445786e-15,-4.136240e-16,-6.306374e-15,4.898456e-15,2.220446e-16,-7.241349e-16,-7.850654e-17,-5.184947e-17,2.478756e-14,5.648223e-15,-7.862371e-16
std,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00,1.001322e+00
min,-4.009161e-01,-4.750375e-01,-1.542098e+00,-2.824395e-01,-1.473054e+00,-3.212411e+00,-2.383692e+00,-1.305175e+00,-9.613082e-01,-1.297643e+00,-2.679512e+00,-4.011372e+00,-1.569360e+00
25%,-3.921019e-01,-4.750375e-01,-8.702290e-01,-2.824395e-01,-8.843599e-01,-6.099797e-01,-8.503718e-01,-8.077409e-01,-6.119929e-01,-7.555694e-01,-6.618926e-01,2.058197e-01,-7.716698e-01
50%,-3.717373e-01,-4.750375e-01,-1.908108e-01,-2.824395e-01,-1.484917e-01,-1.572859e-01,2.842129e-01,-2.286540e-01,-4.955545e-01,-4.388525e-01,1.497932e-01,3.842245e-01,-1.670044e-01
75%,-4.243846e-02,-4.750375e-01,1.078946e+00,-2.824395e-01,5.960339e-01,4.916494e-01,9.131280e-01,6.314225e-01,-1.462393e-01,9.163304e-01,8.455239e-01,4.426258e-01,5.736559e-01
max,1.009914e+01,3.837007e+00,2.534411e+00,3.540581e+00,2.734380e+00,3.688752e+00,1.136058e+00,3.529733e+00,1.716775e+00,1.887798e+00,1.680401e+00,4.426258e-01,3.730053e+00

In [27]:
df4 = pd.DataFrame(x_test_scaled)
df4.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000,127.000000
mean,0.089514,0.162387,0.110071,-0.071722,-0.015770,-0.083888,-0.012199,0.159142,0.136147,0.174343,0.145045,-0.036467,0.111284
std,1.054344,1.209804,1.132636,0.875909,1.012611,1.166140,1.079237,1.224252,1.047794,1.091959,1.008672,1.097564,1.163253
min,-0.400593,-0.475037,-1.584373,-0.282440,-1.343195,-4.070225,-2.271321,-1.280700,-0.961308,-1.303733,-2.493983,-3.985766,-1.392421
25%,-0.390100,-0.475037,-0.874758,-0.282440,-1.014219,-0.624846,-0.879371,-0.863126,-0.611993,-0.700753,-0.267645,0.196723,-0.834549
50%,-0.367484,-0.475037,-0.159105,-0.282440,-0.200435,-0.103765,0.382084,-0.309550,-0.495555,-0.298766,0.381703,0.374790,-0.117286
75%,0.141384,0.432761,1.078946,-0.282440,0.795151,0.394272,0.969313,1.158379,1.716775,1.613717,0.845524,0.427745,0.725736
max,5.633288,4.063957,2.534411,3.540581,2.734380,3.120841,1.136058,4.244420,1.716775,1.887798,1.680401,0.442626,3.585285